#!/usr/bin/env bash

#sudo -v

./scripts/before_install.sh
make
./scripts/install.sh

screen -S 1 ./dnsseed -h seeder.bitcoincore.dev -n ns1.digitalocean.com. -m admin.bitcoincore.dev 2>/dev/null &

if [[ "$OSTYPE" == "linux-gnu" ]]; then
screen -S 2 /usr/sbin/./iftop
elif [[ "$OSTYPE" == "darwin"* ]]; then
screen -S 2 sudo /usr/local/sbin/./iftop
elif [[ "$OSTYPE" == "cygwin" ]]; then
echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "msys" ]]; then
echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "win32" ]]; then
echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "freebsd"* ]]; then
echo TODO add support for $OSTYPE
else
echo TODO add support for $OSTYPE
fi

